In [1]:
library('tidyverse')

── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──

✔ ggplot2 3.2.0     ✔ purrr   0.3.2
✔ tibble  2.1.3     ✔ dplyr   0.8.3
✔ tidyr   0.8.3     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.4.0

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
df.marathon = read.csv('../data/marathon.csv')
df.marathon %>% head

  year name                       country       time       race.time MF
1 2019 Lawrence Cherono           Kenya         2H 7M 57S  2.132500  Men's
2 2018 Yuki Kawauchi              Japan         2H 15M 58S 2.266111  Men's
3 2017 Geoffrey Kirui             Kenya         2H 9M 37S  2.160278  Men's
4 2016 Lemi Berhanu               Ethiopia      2H 12M 45S 2.212500  Men's
5 2015 Lelisa Desisa              Ethiopia      2H 9M 17S  2.154722  Men's
6 2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S  2.143611  Men's
  country.simple
1 Kenya
2 Japan
3 Kenya
4 Ethiopia
5 Ethiopia
6 United States

# Filter

- the filter operation does exactly what you expect given its name.

In [3]:
# e.g.

# iris %>% filter(Species == 'setosa', Petal.Width > 0.2)

- The syntax for the `equals` operator in R is `==`.
- Greater than (`>` or `>=`) and less than (`<` or `<=`) are intuitive.
- You can fitler on multiple columns by adding arguments to the filter operation.

Filter the marathon data to just the runners from Kenya.

In [5]:
df.marathon %>% filter(country == "Kenya") %>% head

  year name                      country time       race.time MF
1 2019 Lawrence Cherono          Kenya   2H 7M 57S  2.132500  Men's
2 2017 Geoffrey Kirui            Kenya   2H 9M 37S  2.160278  Men's
3 2012 Wesley Korir              Kenya   2H 12M 40S 2.211111  Men's
4 2011 Geoffrey Mutai            Kenya   2H 3M 2S   2.050556  Men's
5 2010 Robert Kiprono Cheruiyot  Kenya   2H 5M 52S  2.097778  Men's
6 2008 Robert Kipkoech Cheruiyot Kenya   2H 7M 46S  2.129444  Men's
  country.simple
1 Kenya
2 Kenya
3 Kenya
4 Kenya
5 Kenya
6 Kenya

# How to filter based on multiple criteria

In [4]:
df.marathon %>% filter(country == "Kenya" | country == "Japan") %>% head

  year name                     country time       race.time MF
1 2019 Lawrence Cherono         Kenya   2H 7M 57S  2.132500  Men's
2 2018 Yuki Kawauchi            Japan   2H 15M 58S 2.266111  Men's
3 2017 Geoffrey Kirui           Kenya   2H 9M 37S  2.160278  Men's
4 2012 Wesley Korir             Kenya   2H 12M 40S 2.211111  Men's
5 2011 Geoffrey Mutai           Kenya   2H 3M 2S   2.050556  Men's
6 2010 Robert Kiprono Cheruiyot Kenya   2H 5M 52S  2.097778  Men's
  country.simple
1 Kenya
2 Japan
3 Kenya
4 Kenya
5 Kenya
6 Kenya

In [5]:
df.marathon %>% filter(country %in% c("Kenya", "Japan")) %>% head

  year name                     country time       race.time MF
1 2019 Lawrence Cherono         Kenya   2H 7M 57S  2.132500  Men's
2 2018 Yuki Kawauchi            Japan   2H 15M 58S 2.266111  Men's
3 2017 Geoffrey Kirui           Kenya   2H 9M 37S  2.160278  Men's
4 2012 Wesley Korir             Kenya   2H 12M 40S 2.211111  Men's
5 2011 Geoffrey Mutai           Kenya   2H 3M 2S   2.050556  Men's
6 2010 Robert Kiprono Cheruiyot Kenya   2H 5M 52S  2.097778  Men's
  country.simple
1 Kenya
2 Japan
3 Kenya
4 Kenya
5 Kenya
6 Kenya

In [21]:
tmp1 = df.marathon %>% filter(country == "Kenya")
tmp2 = df.marathon %>% filter(country == "Japan")
rbind(tmp1, tmp2)

   year name                      country time       race.time MF
1  2019 Lawrence Cherono          Kenya   2H 7M 57S  2.132500  Men's
2  2017 Geoffrey Kirui            Kenya   2H 9M 37S  2.160278  Men's
3  2012 Wesley Korir              Kenya   2H 12M 40S 2.211111  Men's
4  2011 Geoffrey Mutai            Kenya   2H 3M 2S   2.050556  Men's
5  2010 Robert Kiprono Cheruiyot  Kenya   2H 5M 52S  2.097778  Men's
6  2008 Robert Kipkoech Cheruiyot Kenya   2H 7M 46S  2.129444  Men's
7  2007 Robert Kipkoech Cheruiyot Kenya   2H 14M 13S 2.236944  Men's
8  2006 Robert Kipkoech Cheruiyot Kenya   2H 7M 14S  2.120556  Men's
9  2004 Timothy Cherigat          Kenya   2H 10M 37S 2.176944  Men's
10 2003 Robert Kipkoech Cheruiyot Kenya   2H 10M 11S 2.169722  Men's
11 2002 Rodgers Rop               Kenya   2H 9M 2S   2.150556  Men's
12 2000 Elijah Lagat              Kenya   2H 9M 47S  2.163056  Men's
13 1999 Joseph Chebet             Kenya   2H 9M 52S  2.164444  Men's
14 1998 Moses Tanui               Kenya   2H 7M 34S  2.126111  Men's
15 1997 Lameck Aguta              Kenya   2H 10M 34S 2.176111  Men's
16 1996 Moses Tanui               Kenya   2H 9M 15S  2.154167  Men's
17 1995 Cosmas Ndeti              Kenya   2H 9M 22S  2.156111  Men's
18 1994 Cosmas Ndeti              Kenya   2H 7M 15S  2.120833  Men's
19 1993 Cosmas Ndeti              Kenya   2H 9M 33S  2.159167  Men's
20 1992 Ibrahim Hussein           Kenya   2H 8M 14S  2.137222  Men's
21 1991 Ibrahim Hussein           Kenya   2H 11M 6S  2.185000  Men's
22 1988 Ibrahim Hussein           Kenya   2H 8M 43S  2.145278  Men's
23 2017 Edna Kiplagat             Kenya   2H 21M 52S 2.364444  Women's
24 2015 Caroline Rotich           Kenya   2H 24M 55S 2.415278  Women's
25 2013 Rita Jeptoo               Kenya   2H 26M 25S 2.440278  Women's
26 2012 Sharon Cherop             Kenya   2H 31M 50S 2.530556  Women's
27 2011 Caroline Kilel            Kenya   2H 22M 36S 2.376667  Women's
28 2009 Salina Kosgei             Kenya   2H 32M 16S 2.537778  Women's
29 2006 Rita Jeptoo               Kenya   2H 23M 38S 2.393889  Women's
30 2005 Catherine Ndereba         Kenya   2H 25M 13S 2.420278  Women's
31 2004 Catherine Ndereba         Kenya   2H 24M 27S 2.407500  Women's
32 2002 Margaret Okayo            Kenya   2H 20M 43S 2.345278  Women's
33 2001 Catherine Ndereba         Kenya   2H 23M 53S 2.398056  Women's
34 2000 Catherine Ndereba         Kenya   2H 26M 11S 2.436389  Women's
35 2018 Yuki Kawauchi             Japan   2H 15M 58S 2.266111  Men's
36 1987 Toshihiko Seko            Japan   2H 11M 50S 2.197222  Men's
37 1981 Toshihiko Seko            Japan   2H 9M 26S  2.157222  Men's
38 1969 Yoshiaki Unetani          Japan   2H 13M 49S 2.230278  Men's
39 1966 Kenji Kimihara            Japan   2H 17M 11S 2.286389  Men's
40 1965 Morio Shigematsu          Japan   2H 16M 33S 2.275833  Men's
41 1955 Hideo Hamamura            Japan   2H 18M 22S 2.306111  Men's
42 1953 Keizo Yamada              Japan   2H 18M 51S 2.314167  Men's
43 1951 Shigeki Tanaka            Japan   2H 27M 45S 2.462500  Men's
   country.simple
1  Kenya
2  Kenya
3  Kenya
4  Kenya
5  Kenya
6  Kenya
7  Kenya
8  Kenya
9  Kenya
10 Kenya
11 Kenya
12 Kenya
13 Kenya
14 Kenya
15 Kenya
16 Kenya
17 Kenya
18 Kenya
19 Kenya
20 Kenya
21 Kenya
22 Kenya
23 Kenya
24 Kenya
25 Kenya
26 Kenya
27 Kenya
28 Kenya
29 Kenya
30 Kenya
31 Kenya
32 Kenya
33 Kenya
34 Kenya
35 Japan
36 Japan
37 Japan
38 Japan
39 Japan
40 Japan
41 Japan
42 Japan
43 Japan

# Select

- select let's you include/exclude columns.

In [4]:
# e.g.

# iris %>% select(Species, Sepal.Length) %>% head

Select just the columns that represent runner names and country from the marathon data.

In [6]:
df.marathon %>% select(name, country) %>% head

  name                       country
1 Lawrence Cherono           Kenya
2 Yuki Kawauchi              Japan
3 Geoffrey Kirui             Kenya
4 Lemi Berhanu               Ethiopia
5 Lelisa Desisa              Ethiopia
6 Mebrahtom "Meb" Keflezighi United States

# Putting it all together

Use `group_by`, `filter`, and `summarize` to show the best race times for US and Kenyan women runners. (*Hint: use the `%in%` operator to filter by two values for one column*). Fill in the missing pieces below:

In [5]:
df.marathon %>%
    filter(MF == "Women's", country %in% c("United States", "Kenya")) %>%
    group_by(country) %>%
    summarize(best.race.time = min(race.time))

Use `filter`, `select`, `head`, and `arrange` to show the best women's race times in the data and the country of the runners. Fill in the missing pieces below:

In [11]:
df.marathon %>%
    filter(MF == "Women's") %>%
    select(race.time, country) %>%
    arrange(-race.time) %>%
    head()

  race.time country
1 3.173889  United States
2 3.099722  United States
3 2.809167  United States
4 2.786389  United States
5 2.786111  United States
6 2.747778  United States

In [12]:
df.marathon %>%
    filter(MF == "Women's") %>%
    select(race.time, country) %>%
    arrange(desc(race.time)) %>%
    head()

  race.time country
1 3.173889  United States
2 3.099722  United States
3 2.809167  United States
4 2.786389  United States
5 2.786111  United States
6 2.747778  United States

What's the best race time ever for a US man?

In [13]:
df.marathon %>%
    filter(MF == "Men's", country == "United States") %>%
    arrange(race.time) %>%
    head(1)

  year name                       country       time      race.time MF
1 2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S 2.143611  Men's
  country.simple
1 United States

In [16]:
df.marathon %>%
    filter(MF == "Men's", country == "United States") %>%
    top_n(1, -race.time)

  year name                       country       time      race.time MF
1 2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S 2.143611  Men's
  country.simple
1 United States

How does the best US men's time compare the the best race time in the data overall?

In [17]:
df.marathon %>%
    filter(MF == "Men's") %>%
    top_n(1, -race.time)

# It is less than the best overall time.

  year name           country time     race.time MF    country.simple
1 2011 Geoffrey Mutai Kenya   2H 3M 2S 2.050556  Men's Kenya

# Bonus

For all countries with at least 5 winners in the men's category, which country has the best median race time in the men's category? (*Hint: use the `n()` function to count the winners by country.)

In [22]:
# This should get you started. It adds a column "N.winners" that represents the
# total winners from the runner's country.

df.marathon %>%
    filter(MF == "Men's") %>%
    group_by(country) %>%
    mutate(N.winners = n(), Median = median(race.time)) %>% 
    filter(N.winners >= 5) %>%
    arrange(Median) %>%
    head()

# Kenya has best median time!

    year name                        country       time       race.time MF
1   2019 Lawrence Cherono            Kenya         2H 7M 57S  2.132500  Men's
2   2017 Geoffrey Kirui              Kenya         2H 9M 37S  2.160278  Men's
3   2012 Wesley Korir                Kenya         2H 12M 40S 2.211111  Men's
4   2011 Geoffrey Mutai              Kenya         2H 3M 2S   2.050556  Men's
5   2010 Robert Kiprono Cheruiyot    Kenya         2H 5M 52S  2.097778  Men's
6   2008 Robert Kipkoech Cheruiyot   Kenya         2H 7M 46S  2.129444  Men's
7   2007 Robert Kipkoech Cheruiyot   Kenya         2H 14M 13S 2.236944  Men's
8   2006 Robert Kipkoech Cheruiyot   Kenya         2H 7M 14S  2.120556  Men's
9   2004 Timothy Cherigat            Kenya         2H 10M 37S 2.176944  Men's
10  2003 Robert Kipkoech Cheruiyot   Kenya         2H 10M 11S 2.169722  Men's
11  2002 Rodgers Rop                 Kenya         2H 9M 2S   2.150556  Men's
12  2000 Elijah Lagat                Kenya         2H 9M 47S  2.163056  Men's
13  1999 Joseph Chebet               Kenya         2H 9M 52S  2.164444  Men's
14  1998 Moses Tanui                 Kenya         2H 7M 34S  2.126111  Men's
15  1997 Lameck Aguta                Kenya         2H 10M 34S 2.176111  Men's
16  1996 Moses Tanui                 Kenya         2H 9M 15S  2.154167  Men's
17  1995 Cosmas Ndeti                Kenya         2H 9M 22S  2.156111  Men's
18  1994 Cosmas Ndeti                Kenya         2H 7M 15S  2.120833  Men's
19  1993 Cosmas Ndeti                Kenya         2H 9M 33S  2.159167  Men's
20  1992 Ibrahim Hussein             Kenya         2H 8M 14S  2.137222  Men's
21  1991 Ibrahim Hussein             Kenya         2H 11M 6S  2.185000  Men's
22  1988 Ibrahim Hussein             Kenya         2H 8M 43S  2.145278  Men's
23  2016 Lemi Berhanu                Ethiopia      2H 12M 45S 2.212500  Men's
24  2015 Lelisa Desisa               Ethiopia      2H 9M 17S  2.154722  Men's
25  2013 Lelisa Desisa               Ethiopia      2H 10M 22S 2.172778  Men's
26  2009 Deriba Merga                Ethiopia      2H 8M 42S  2.145000  Men's
27  2005 Hailu Negussie              Ethiopia      2H 11M 45S 2.195833  Men's
28  1989 Abebe Mekonnen              Ethiopia      2H 9M 6S   2.151667  Men's
29  2018 Yuki Kawauchi               Japan         2H 15M 58S 2.266111  Men's
30  1987 Toshihiko Seko              Japan         2H 11M 50S 2.197222  Men's
⋮   ⋮    ⋮                           ⋮             ⋮          ⋮         ⋮
71  1922 Clarence H. DeMar           United States 2H 18M 10S 2.302778  Men's
72  1921 Frank T. Zuna               United States 2H 18M 57S 2.315833  Men's
73  1919 Carl W. A. Linder           United States 2H 29M 13S 2.486944  Men's
74  1918 Camp Devens Divisional Team United States 2H 24M 53S 2.414722  Men's
75  1917 William J. (Bill) Kennedy   United States 2H 28M 37S 2.476944  Men's
76  1916 Arthur V. Roth              United States 2H 27M 16S 2.454444  Men's
77  1913 Fritz Carlson               United States 2H 25M 14S 2.420556  Men's
78  1912 Michael J. Ryan             United States 2H 21M 18S 2.355000  Men's
79  1911 Clarence H. DeMar           United States 2H 21M 39S 2.360833  Men's
80  1909 Henri Renaud                United States 2H 53M 36S 2.893333  Men's
81  1908 Thomas P. Morrissey         United States 2H 25M 43S 2.428611  Men's
82  1906 Timothy Ford                United States 2H 45M 45S 2.762500  Men's
83  1905 Frederick Lorz              United States 2H 38M 25S 2.640278  Men's
84  1904 Michael Spring              United States 2H 38M 4S  2.634444  Men's
85  1903 John C. Lorden              United States 2H 41M 29S 2.691389  Men's
86  1902 Sammy A. Mellor             United States 2H 43M 12S 2.720000  Men's
87  1899 Lawrence Brignolia          United States 2H 54M 38S 2.910556  Men's
88  1897 John J. McDermott           United States 2H 55M 10S 2.919444  Men's
89  1977 Jerome Drayton              Canada        2H 14M 46S 2.246111  Men's
90  1948 Gerard Cote                 Canada        2H 31M 2S  2.517222  Men's
91  1944 Gerard Cote                 Canada        2H 31M 50S 2.530556  Men's
92  1943 Gerard Cote                 Canada        2H 28M 25S 2.473611  Men's
93  1940 Gerard Cote                 Canada        2H 28M 28S 2.474444  Men's
94  1937 Walter Young                Canada        2H 33M 20S 2.555556  Men's
95  1934 Dave Komonen                Canada        2H 32M 53S 2.548056  Men's
96  1929 John C. Miles               Canada        2H 33M 8S  2.552222  Men's
97  1926 John C. Miles               Canada        2H 25M 40S 2.427778  Men's
98  1915 Edouard Fabre               Canada        2H 31M 41S 2.528056  Men's
99  1914 James Duffy                 Canada        2H 25M 1S  2.416944  Men's
100 1910 Fred L. Cameron             Canada        2H 28M 52S 2.481111  Men's
    country.simple N.winners Median
1   Kenya          22        2.155139
2   Kenya          22        2.155139
3   Kenya          22        2.155139
4   Kenya          22        2.155139
5   Kenya          22        2.155139
6   Kenya          22        2.155139
7   Kenya          22        2.155139
8   Kenya          22        2.155139
9   Kenya          22        2.155139
10  Kenya          22        2.155139
11  Kenya          22        2.155139
12  Kenya          22        2.155139
13  Kenya          22        2.155139
14  Kenya          22        2.155139
15  Kenya          22        2.155139
16  Kenya          22        2.155139
17  Kenya          22        2.155139
18  Kenya          22        2.155139
19  Kenya          22        2.155139
20  Kenya          22        2.155139
21  Kenya          22        2.155139
22  Kenya          22        2.155139
23  Ethiopia        6        2.163750
24  Ethiopia        6        2.163750
25  Ethiopia        6        2.163750
26  Ethiopia        6        2.163750
27  Ethiopia        6        2.163750
28  Ethiopia        6        2.163750
29  Japan           9        2.275833
30  Japan           9        2.275833
⋮   ⋮              ⋮         ⋮
71  United States  44        2.478889
72  United States  44        2.478889
73  United States  44        2.478889
74  United States  44        2.478889
75  United States  44        2.478889
76  United States  44        2.478889
77  United States  44        2.478889
78  United States  44        2.478889
79  United States  44        2.478889
80  United States  44        2.478889
81  United States  44        2.478889
82  United States  44        2.478889
83  United States  44        2.478889
84  United States  44        2.478889
85  United States  44        2.478889
86  United States  44        2.478889
87  United States  44        2.478889
88  United States  44        2.478889
89  other          16        2.503472
90  other          16        2.503472
91  other          16        2.503472
92  other          16        2.503472
93  other          16        2.503472
94  other          16        2.503472
95  other          16        2.503472
96  other          16        2.503472
97  other          16        2.503472
98  other          16        2.503472
99  other          16        2.503472
100 other          16        2.503472

In [24]:
tmp1 = df.marathon %>%
    filter(MF == "Men's") %>%
    group_by(country) %>%
    count() %>%
    filter(n >= 5)

countries.gt5 = tmp1$country

df.marathon %>%
    filter(country %in% countries.gt5)

    year name                       country       time       race.time MF
1   2019 Lawrence Cherono           Kenya         2H 7M 57S  2.132500  Men's
2   2018 Yuki Kawauchi              Japan         2H 15M 58S 2.266111  Men's
3   2017 Geoffrey Kirui             Kenya         2H 9M 37S  2.160278  Men's
4   2016 Lemi Berhanu               Ethiopia      2H 12M 45S 2.212500  Men's
5   2015 Lelisa Desisa              Ethiopia      2H 9M 17S  2.154722  Men's
6   2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S  2.143611  Men's
7   2013 Lelisa Desisa              Ethiopia      2H 10M 22S 2.172778  Men's
8   2012 Wesley Korir               Kenya         2H 12M 40S 2.211111  Men's
9   2011 Geoffrey Mutai             Kenya         2H 3M 2S   2.050556  Men's
10  2010 Robert Kiprono Cheruiyot   Kenya         2H 5M 52S  2.097778  Men's
11  2009 Deriba Merga               Ethiopia      2H 8M 42S  2.145000  Men's
12  2008 Robert Kipkoech Cheruiyot  Kenya         2H 7M 46S  2.129444  Men's
13  2007 Robert Kipkoech Cheruiyot  Kenya         2H 14M 13S 2.236944  Men's
14  2006 Robert Kipkoech Cheruiyot  Kenya         2H 7M 14S  2.120556  Men's
15  2005 Hailu Negussie             Ethiopia      2H 11M 45S 2.195833  Men's
16  2004 Timothy Cherigat           Kenya         2H 10M 37S 2.176944  Men's
17  2003 Robert Kipkoech Cheruiyot  Kenya         2H 10M 11S 2.169722  Men's
18  2002 Rodgers Rop                Kenya         2H 9M 2S   2.150556  Men's
19  2000 Elijah Lagat               Kenya         2H 9M 47S  2.163056  Men's
20  1999 Joseph Chebet              Kenya         2H 9M 52S  2.164444  Men's
21  1998 Moses Tanui                Kenya         2H 7M 34S  2.126111  Men's
22  1997 Lameck Aguta               Kenya         2H 10M 34S 2.176111  Men's
23  1996 Moses Tanui                Kenya         2H 9M 15S  2.154167  Men's
24  1995 Cosmas Ndeti               Kenya         2H 9M 22S  2.156111  Men's
25  1994 Cosmas Ndeti               Kenya         2H 7M 15S  2.120833  Men's
26  1993 Cosmas Ndeti               Kenya         2H 9M 33S  2.159167  Men's
27  1992 Ibrahim Hussein            Kenya         2H 8M 14S  2.137222  Men's
28  1991 Ibrahim Hussein            Kenya         2H 11M 6S  2.185000  Men's
29  1989 Abebe Mekonnen             Ethiopia      2H 9M 6S   2.151667  Men's
30  1988 Ibrahim Hussein            Kenya         2H 8M 43S  2.145278  Men's
⋮   ⋮    ⋮                          ⋮             ⋮          ⋮         ⋮
106 2018 Desiree Linden             United States 2H 39M 54S 2.665000  Women's
107 2017 Edna Kiplagat              Kenya         2H 21M 52S 2.364444  Women's
108 2016 Atsede Baysa               Ethiopia      2H 29M 19S 2.488611  Women's
109 2015 Caroline Rotich            Kenya         2H 24M 55S 2.415278  Women's
110 2014 Buzunesh Deba              Ethiopia      2H 19M 59S 2.333056  Women's
111 2013 Rita Jeptoo                Kenya         2H 26M 25S 2.440278  Women's
112 2012 Sharon Cherop              Kenya         2H 31M 50S 2.530556  Women's
113 2011 Caroline Kilel             Kenya         2H 22M 36S 2.376667  Women's
114 2010 Teyba Erkesso              Ethiopia      2H 26M 11S 2.436389  Women's
115 2009 Salina Kosgei              Kenya         2H 32M 16S 2.537778  Women's
116 2008 Dire Tune                  Ethiopia      2H 25M 25S 2.423611  Women's
117 2006 Rita Jeptoo                Kenya         2H 23M 38S 2.393889  Women's
118 2005 Catherine Ndereba          Kenya         2H 25M 13S 2.420278  Women's
119 2004 Catherine Ndereba          Kenya         2H 24M 27S 2.407500  Women's
120 2002 Margaret Okayo             Kenya         2H 20M 43S 2.345278  Women's
121 2001 Catherine Ndereba          Kenya         2H 23M 53S 2.398056  Women's
122 2000 Catherine Ndereba          Kenya         2H 26M 11S 2.436389  Women's
123 1999 Fatuma Roba                Ethiopia      2H 23M 25S 2.390278  Women's
124 1998 Fatuma Roba                Ethiopia      2H 23M 21S 2.389167  Women's
125 1997 Fatuma Roba                Ethiopia      2H 26M 23S 2.439722  Women's
126 1985 Lisa Larsen-Weidenbach     United States 2H 34M 6S  2.568333  Women's
127 1983 Joan Benoit                United States 2H 22M 43S 2.378611  Women's
128 1980 Jacqueline Gareau          Canada        2H 34M 28S 2.574444  Women's
129 1979 Joan Benoit                United States 2H 35M 15S 2.587500  Women's
130 1978 Gayle S. Barron            United States 2H 44M 52S 2.747778  Women's
131 1977 Michiko (Miki) Gorman      United States 2H 48M 33S 2.809167  Women's
132 1976 Kim Merritt                United States 2H 47M 10S 2.786111  Women's
133 1974 Michiko (Miki) Gorman      United States 2H 47M 11S 2.786389  Women's
134 1973 Jacqueline A. Hansen       United States 3H 5M 59S  3.099722  Women's
135 1972 Nina Kuscsik               United States 3H 10M 26S 3.173889  Women's
    country.simple
1   Kenya
2   Japan
3   Kenya
4   Ethiopia
5   Ethiopia
6   United States
7   Ethiopia
8   Kenya
9   Kenya
10  Kenya
11  Ethiopia
12  Kenya
13  Kenya
14  Kenya
15  Ethiopia
16  Kenya
17  Kenya
18  Kenya
19  Kenya
20  Kenya
21  Kenya
22  Kenya
23  Kenya
24  Kenya
25  Kenya
26  Kenya
27  Kenya
28  Kenya
29  Ethiopia
30  Kenya
⋮   ⋮
106 United States
107 Kenya
108 Ethiopia
109 Kenya
110 Ethiopia
111 Kenya
112 Kenya
113 Kenya
114 Ethiopia
115 Kenya
116 Ethiopia
117 Kenya
118 Kenya
119 Kenya
120 Kenya
121 Kenya
122 Kenya
123 Ethiopia
124 Ethiopia
125 Ethiopia
126 United States
127 United States
128 other
129 United States
130 United States
131 United States
132 United States
133 United States
134 United States
135 United States

In [33]:
df.marathon %>%
    filter(MF == "Men's") %>%
    group_by(country) %>%
    mutate(N.winners=n()) %>%
    filter(N.winners >= 5) %>%
    summarize(median.race.time = median(race.time)) %>%
    arrange(median.race.time)

  country       median.race.time
1 Kenya         2.155139
2 Ethiopia      2.163750
3 Japan         2.275833
4 Finland       2.348333
5 United States 2.478889
6 Canada        2.503472